version: '3'
services:
  db:
    container_name: db
    image: postgis/postgis:14-3.3-alpine
    restart: always
    environment:
      POSTGRES_DB: food-twin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./app-data/postgresql:/var/lib/postgresql/data
